version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    restart: 'always'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./symfony/:/var/www/symfony:cached']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'formation-phpmyadmin'
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '8081:80'
    volumes:
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

  redis:
    container_name: 'formation-redis'
    image: redis:latest
    ports:
      - "127.0.0.1:6397:6379"